/**
 * Types Command
 * Generate TypeScript type definitions for Shift CSS attributes
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import pc from 'picocolors';

type Framework = 'react' | 'vue' | 'svelte' | 'unknown';

interface TypesOptions {
	framework?: Framework;
	output?: string;
}

/**
 * Detect frontend framework from package.json
 */
function detectFramework(rootDir: string): Framework {
	const pkgPath = join(rootDir, 'package.json');

	if (!existsSync(pkgPath)) {
		return 'unknown';
	}

	try {
		const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
		const deps = {
			...pkg.dependencies,
			...pkg.devDependencies,
		};

		if (deps.react || deps['react-dom'] || deps.next) {
			return 'react';
		}

		if (deps.vue || deps.nuxt) {
			return 'vue';
		}

		if (deps.svelte || deps['@sveltejs/kit']) {
			return 'svelte';
		}
	} catch {
		// Ignore parse errors
	}

	return 'unknown';
}

/**
 * Generate React type reference content
 */
function generateReactTypes(): string {
	return `/**
 * Shift CSS - React Type Definitions
 *
 * This file enables TypeScript support for Shift CSS attributes in JSX.
 * Generated by: npx shift-css types
 */

/// <reference types="@shift-css/core/types/react" />
`;
}

/**
 * Generate Vue type reference content
 */
function generateVueTypes(): string {
	return `/**
 * Shift CSS - Vue Type Definitions
 *
 * This file enables TypeScript support for Shift CSS attributes in Vue templates.
 * Generated by: npx shift-css types
 */

/// <reference types="@shift-css/core/types/vue" />
`;
}

/**
 * Generate generic type reference content
 */
function generateGenericTypes(): string {
	return `/**
 * Shift CSS - Type Definitions
 *
 * Import the types you need for your framework:
 *
 * React:
 *   /// <reference types="@shift-css/core/types/react" />
 *
 * Vue:
 *   /// <reference types="@shift-css/core/types/vue" />
 *
 * Generated by: npx shift-css types
 */

// Uncomment the line for your framework:
// /// <reference types="@shift-css/core/types/react" />
// /// <reference types="@shift-css/core/types/vue" />

export {};
`;
}

/**
 * Show usage instructions
 */
function showInstructions(framework: Framework): void {
	console.log();
	console.log(pc.bold('📝 Next Steps'));
	console.log();

	if (framework === 'react') {
		console.log(pc.dim('Option 1: Add to tsconfig.json (recommended)'));
		console.log();
		console.log(pc.cyan('  {'));
		console.log(pc.cyan('    "compilerOptions": {'));
		console.log(pc.cyan('      "types": ["@shift-css/core/types/react"]'));
		console.log(pc.cyan('    }'));
		console.log(pc.cyan('  }'));
		console.log();
		console.log(pc.dim('Option 2: Add reference to any .d.ts file'));
		console.log();
		console.log(pc.cyan('  /// <reference types="@shift-css/core/types/react" />'));
	} else if (framework === 'vue') {
		console.log(pc.dim('Option 1: Add to tsconfig.json (recommended)'));
		console.log();
		console.log(pc.cyan('  {'));
		console.log(pc.cyan('    "compilerOptions": {'));
		console.log(pc.cyan('      "types": ["@shift-css/core/types/vue"]'));
		console.log(pc.cyan('    }'));
		console.log(pc.cyan('  }'));
		console.log();
		console.log(pc.dim('Option 2: Add reference to any .d.ts file'));
		console.log();
		console.log(pc.cyan('  /// <reference types="@shift-css/core/types/vue" />'));
	} else if (framework === 'svelte') {
		console.log(pc.dim('Svelte support is coming soon!'));
		console.log();
		console.log(pc.dim('For now, you can generate a local .d.ts file:'));
		console.log();
		console.log(pc.cyan('  npx shift-css types --svelte -o shift.d.ts'));
	} else {
		console.log(pc.dim('Add to your tsconfig.json based on your framework:'));
		console.log();
		console.log(pc.cyan('  React:  "types": ["@shift-css/core/types/react"]'));
		console.log(pc.cyan('  Vue:    "types": ["@shift-css/core/types/vue"]'));
		console.log(pc.cyan('  Svelte: Coming soon'));
	}

	console.log();
	console.log(pc.dim("After setup, you'll get autocomplete for attributes like:"));
	console.log(pc.green('  s-btn="primary"  s-grid="3"  s-flex="center"'));
	console.log();
}

/**
 * Main types command
 */
export async function typesCommand(options: TypesOptions = {}): Promise<void> {
	const rootDir = process.cwd();

	console.log();
	console.log(pc.bold('🎨 Shift CSS Type Generator'));
	console.log();

	// Detect or use specified framework
	const framework = options.framework || detectFramework(rootDir);

	if (framework !== 'unknown') {
		console.log(`${pc.green('✓')} Detected framework: ${pc.cyan(framework)}`);
	} else {
		console.log(`${pc.yellow('!')} Could not detect framework automatically`);
	}

	// Generate and write type file if output specified
	if (options.output) {
		const outputPath = join(rootDir, options.output);

		let content: string;
		switch (framework) {
			case 'react':
				content = generateReactTypes();
				break;
			case 'vue':
				content = generateVueTypes();
				break;
			default:
				content = generateGenericTypes();
		}

		try {
			writeFileSync(outputPath, content, 'utf-8');
			console.log(`${pc.green('✓')} Created ${pc.cyan(options.output)}`);
		} catch (error) {
			console.error(`${pc.red('✗')} Failed to write ${options.output}`);
			if (error instanceof Error) {
				console.error(pc.dim(error.message));
			}
			process.exit(1);
		}
	}

	// Show instructions
	showInstructions(framework);
}
